
// This file has been generated by the GUI designer. Do not modify.
namespace DistributionsGTK
{
	public partial class TransformWindow
	{
		private global::Gtk.HPaned hpaned2;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label5;

		private global::Gtk.Entry txtEquation;

		private global::Gtk.Button btnSolve;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox propsMath;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label1;

		private global::Gtk.SpinButton numSamples;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label2;

		private global::Gtk.SpinButton numSensitivity;

		private global::Gtk.CheckButton checkMath;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox propsMonteCarlo;

		private global::Gtk.HBox hbox6;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label3;

		private global::Gtk.SpinButton numRandoms;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label4;

		private global::Gtk.SpinButton numPockets;

		private global::Gtk.CheckButton checkMonteCarlo;

		private global::Gtk.Frame frame3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.DrawingArea chartPDF;

		private global::Gtk.DrawingArea chartCDF;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeUnivariateSettings;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DistributionsGTK.TransformWindow
			this.Name = "DistributionsGTK.TransformWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("TransformWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DistributionsGTK.TransformWindow.Gtk.Container+ContainerChild
			this.hpaned2 = new global::Gtk.HPaned();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 856;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(6));
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Модель");
			this.hbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtEquation = new global::Gtk.Entry();
			this.txtEquation.CanFocus = true;
			this.txtEquation.Name = "txtEquation";
			this.txtEquation.Text = global::Mono.Unix.Catalog.GetString("A+B*3+1");
			this.txtEquation.IsEditable = true;
			this.txtEquation.InvisibleChar = '●';
			this.hbox2.Add(this.txtEquation);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtEquation]));
			w2.Position = 1;
			w2.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnSolve = new global::Gtk.Button();
			this.btnSolve.CanFocus = true;
			this.btnSolve.Name = "btnSolve";
			this.btnSolve.UseUnderline = true;
			this.btnSolve.Label = global::Mono.Unix.Catalog.GetString("Расчёт");
			this.hbox2.Add(this.btnSolve);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnSolve]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.BorderWidth = ((uint)(6));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(3));
			// Container child vbox2.Gtk.Box+BoxChild
			this.propsMath = new global::Gtk.HBox();
			this.propsMath.Name = "propsMath";
			this.propsMath.Homogeneous = true;
			this.propsMath.Spacing = 6;
			// Container child propsMath.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Отсчётов");
			this.vbox3.Add(this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.numSamples = new global::Gtk.SpinButton(3D, 10000000D, 1D);
			this.numSamples.CanFocus = true;
			this.numSamples.Name = "numSamples";
			this.numSamples.Adjustment.PageIncrement = 10D;
			this.numSamples.ClimbRate = 1D;
			this.numSamples.Numeric = true;
			this.numSamples.Value = 1000D;
			this.vbox3.Add(this.numSamples);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.numSamples]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.propsMath.Add(this.vbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.propsMath[this.vbox3]));
			w7.Position = 0;
			// Container child propsMath.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Чувствительность");
			this.vbox4.Add(this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.numSensitivity = new global::Gtk.SpinButton(0D, 1D, 1D);
			this.numSensitivity.CanFocus = true;
			this.numSensitivity.Name = "numSensitivity";
			this.numSensitivity.Adjustment.PageIncrement = 10D;
			this.numSensitivity.ClimbRate = 0.0001D;
			this.numSensitivity.Digits = ((uint)(6));
			this.numSensitivity.Numeric = true;
			this.numSensitivity.Value = 0.0001D;
			this.vbox4.Add(this.numSensitivity);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.numSensitivity]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.propsMath.Add(this.vbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.propsMath[this.vbox4]));
			w10.Position = 1;
			this.vbox2.Add(this.propsMath);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.propsMath]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.GtkAlignment.Add(this.vbox2);
			this.frame1.Add(this.GtkAlignment);
			this.checkMath = new global::Gtk.CheckButton();
			this.checkMath.Name = "checkMath";
			this.checkMath.Label = global::Mono.Unix.Catalog.GetString("Численно-аналитический");
			this.checkMath.Active = true;
			this.checkMath.DrawIndicator = true;
			this.frame1.LabelWidget = this.checkMath;
			this.hbox4.Add(this.frame1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.frame1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.BorderWidth = ((uint)(6));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.propsMonteCarlo = new global::Gtk.VBox();
			this.propsMonteCarlo.Name = "propsMonteCarlo";
			this.propsMonteCarlo.Spacing = 6;
			this.propsMonteCarlo.BorderWidth = ((uint)(3));
			// Container child propsMonteCarlo.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Случайных величин");
			this.vbox6.Add(this.label3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label3]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.numRandoms = new global::Gtk.SpinButton(10D, 100000000D, 1D);
			this.numRandoms.CanFocus = true;
			this.numRandoms.Name = "numRandoms";
			this.numRandoms.Adjustment.PageIncrement = 10D;
			this.numRandoms.ClimbRate = 1D;
			this.numRandoms.Numeric = true;
			this.numRandoms.Value = 1000000D;
			this.vbox6.Add(this.numRandoms);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.numRandoms]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox6.Add(this.vbox6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox6]));
			w17.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Отсчётов (графики)");
			this.vbox7.Add(this.label4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label4]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.numPockets = new global::Gtk.SpinButton(3D, 10000000D, 1D);
			this.numPockets.CanFocus = true;
			this.numPockets.Name = "numPockets";
			this.numPockets.Adjustment.PageIncrement = 10D;
			this.numPockets.ClimbRate = 1D;
			this.numPockets.Numeric = true;
			this.numPockets.Value = 100D;
			this.vbox7.Add(this.numPockets);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.numPockets]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox6.Add(this.vbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox7]));
			w20.Position = 1;
			this.propsMonteCarlo.Add(this.hbox6);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.propsMonteCarlo[this.hbox6]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			this.GtkAlignment1.Add(this.propsMonteCarlo);
			this.frame2.Add(this.GtkAlignment1);
			this.checkMonteCarlo = new global::Gtk.CheckButton();
			this.checkMonteCarlo.Name = "checkMonteCarlo";
			this.checkMonteCarlo.Label = global::Mono.Unix.Catalog.GetString("Монте-Карло");
			this.checkMonteCarlo.DrawIndicator = true;
			this.frame2.LabelWidget = this.checkMonteCarlo;
			this.hbox4.Add(this.frame2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.frame2]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			this.hbox4.Add(this.frame3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.frame3]));
			w25.Position = 2;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chartPDF = new global::Gtk.DrawingArea();
			this.chartPDF.Name = "chartPDF";
			this.hbox3.Add(this.chartPDF);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.chartPDF]));
			w27.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.chartCDF = new global::Gtk.DrawingArea();
			this.chartCDF.Name = "chartCDF";
			this.hbox3.Add(this.chartCDF);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.chartCDF]));
			w28.Position = 1;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w29.Position = 2;
			this.hpaned2.Add(this.vbox1);
			global::Gtk.Paned.PanedChild w30 = ((global::Gtk.Paned.PanedChild)(this.hpaned2[this.vbox1]));
			w30.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeUnivariateSettings = new global::Gtk.TreeView();
			this.treeUnivariateSettings.CanFocus = true;
			this.treeUnivariateSettings.Name = "treeUnivariateSettings";
			this.GtkScrolledWindow.Add(this.treeUnivariateSettings);
			this.hpaned2.Add(this.GtkScrolledWindow);
			this.Add(this.hpaned2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1114;
			this.DefaultHeight = 536;
			this.Show();
			this.btnSolve.Clicked += new global::System.EventHandler(this.OnBtnSolveClicked);
			this.treeUnivariateSettings.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTreeUnivariateSettingsRowActivated);
		}
	}
}
